name: DB Fahrplan Alerts

on:
  schedule:
    - cron: '*/15 * * * *'  # alle 15 Minuten
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # libcurl headers (f端r R-Paket 'curl'), pkg-config f端r die Erkennung
          # libxml2-dev f端r xml2, libssl-dev f端r OpenSSL-basierte Pakete
          sudo apt-get install -y libcurl4-openssl-dev pkg-config libxml2-dev libssl-dev

      - name: Install R packages
        run: |
          R -e 'install.packages(c("httr","xml2","dplyr","purrr","tibble","lubridate"), dependencies=TRUE, repos="https://cloud.r-project.org")'

      - name: Set environment variables
        run: |
          echo "DB_API=${{ secrets.DB_API }}" >> $GITHUB_ENV
          echo "Telegram_BOT=${{ secrets.Telegram_BOT }}" >> $GITHUB_ENV
          echo "Telegram_CHAT=${{ secrets.Telegram_CHAT }}" >> $GITHUB_ENV

      - name: Run DB alert script
        run: Rscript main.R
